module.exports = {
  '@primary-color': '#FF4A5C',
  '@component-background': '#fff',
  '@layout-sider-background': '#fff',
  '@layout-header-height': '50px',
  '@layout-header-background': '#fff',
  '@layout-trigger-background': '#FF4A5C',
  '@layout-trigger-height': '40px',
  '@layout-trigger-color': '#fff',
  '@shadow-color': 'rgba(0, 0, 0, 0.15)',
  '@btn-height-base': '28px',
  '@btn-height-lg': '36px',
  '@btn-height-sm': '24px',
  '@input-height-base': '28px',
  '@input-height-lg': '36px',
  '@input-height-sm': '24px',
  '@border-radius-base': '2px',
  '@table-padding-vertical': '11px',
  '@table-padding-vertical-md': '11px',
  '@table-padding-horizontal': '16px',
  '@table-padding-horizontal-md': '16px',
  '@modal-body-padding': '14px',
  '@modal-header-bg': '#fff',
  '@modal-footer-bg': '#F2F4F7',
  '@form-item-margin-bottom': '10px'
}
